"""
Generates the submission deck from docs/facts.json.

Every number on every slide is read from that file, which is itself generated by
`npx tsx scripts/facts.ts` straight out of the computation layer. Nothing is
typed by hand, so the deck cannot claim something the product does not compute.

Run (after regenerating facts):
    cd web && npx tsx scripts/facts.ts
    cd py-service && python build_deck.py

Out: ../docs/Nightline.pptx
"""

from __future__ import annotations

import json
import os

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Emu, Inches, Pt

HERE = os.path.dirname(os.path.abspath(__file__))
FACTS = os.path.join(HERE, "..", "docs", "facts.json")
SHOTS = os.path.join(HERE, "..", "docs", "shots")
OUT = os.path.join(HERE, "..", "docs", "Nightline.pptx")

# Matches the app's dark theme so the deck and the demo read as one product.
BG = RGBColor(0x0B, 0x0F, 0x14)
CARD = RGBColor(0x15, 0x1B, 0x24)
FG = RGBColor(0xF1, 0xF5, 0xF9)
MUTED = RGBColor(0x8B, 0x99, 0xA9)
GREEN = RGBColor(0x22, 0xC5, 0x5E)
RED = RGBColor(0xEF, 0x44, 0x44)
AMBER = RGBColor(0xF5, 0x9E, 0x0B)

W, H = Inches(13.333), Inches(7.5)


def load() -> dict:
    with open(FACTS, encoding="utf-8") as f:
        return json.load(f)


def blank(prs: Presentation):
    s = prs.slides.add_slide(prs.slide_layouts[6])
    bg = s.background.fill
    bg.solid()
    bg.fore_color.rgb = BG
    return s


def text(
    slide,
    txt,
    x,
    y,
    w,
    h,
    size=18,
    color=FG,
    bold=False,
    align=PP_ALIGN.LEFT,
    spacing=1.15,
):
    box = slide.shapes.add_textbox(x, y, w, h)
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0

    lines = txt.split("\n") if isinstance(txt, str) else list(txt)
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        p.line_spacing = spacing
        run = p.add_run()
        run.text = line
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = color
        run.font.name = "Segoe UI"
    return box


def card(slide, x, y, w, h, fill=CARD):
    from pptx.enum.shapes import MSO_SHAPE

    sh = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, x, y, w, h)
    sh.fill.solid()
    sh.fill.fore_color.rgb = fill
    sh.line.fill.background()
    sh.shadow.inherit = False
    sh.text_frame.text = ""
    return sh


def stat_card(slide, x, y, w, value, label, color=FG, sub=None):
    h = Inches(1.55 if sub else 1.25)
    card(slide, x, y, w, h)
    text(slide, value, x + Inches(0.25), y + Inches(0.18), w - Inches(0.5), Inches(0.6),
         size=30, color=color, bold=True)
    text(slide, label, x + Inches(0.25), y + Inches(0.78), w - Inches(0.5), Inches(0.45),
         size=12, color=MUTED)
    if sub:
        text(slide, sub, x + Inches(0.25), y + Inches(1.12), w - Inches(0.5), Inches(0.35),
             size=10, color=MUTED)


def header(slide, kicker, title):
    text(slide, kicker, Inches(0.8), Inches(0.55), Inches(11), Inches(0.3),
         size=12, color=GREEN, bold=True)
    text(slide, title, Inches(0.8), Inches(0.95), Inches(11.7), Inches(0.9),
         size=32, color=FG, bold=True)


def bullets(slide, items, x, y, w, size=15, gap=0.62):
    for i, (head, body) in enumerate(items):
        yy = y + Inches(i * gap * 1.55)
        text(slide, head, x, yy, w, Inches(0.32), size=size, color=FG, bold=True)
        text(slide, body, x, yy + Inches(0.32), w, Inches(0.55), size=size - 3, color=MUTED)


def maybe_image(slide, name, x, y, w):
    """Drops in a screenshot if one has been saved, else a labelled placeholder."""
    for ext in (".png", ".jpg", ".jpeg"):
        p = os.path.join(SHOTS, name + ext)
        if os.path.exists(p):
            slide.shapes.add_picture(p, x, y, width=w)
            return True
    h = Emu(int(w * 0.58))
    card(slide, x, y, w, h, fill=RGBColor(0x1A, 0x21, 0x2B))
    text(slide, f"[ screenshot: {name} ]", x, y + Emu(int(h / 2)) - Inches(0.15), w,
         Inches(0.3), size=12, color=MUTED, align=PP_ALIGN.CENTER)
    return False


# ---------------------------------------------------------------- slides


def s_title(prs, f):
    s = blank(prs)
    text(s, "HACKS 11.0  ·  Problem Statement 17  ·  Smart Cities",
         Inches(0.9), Inches(2.3), Inches(11), Inches(0.35), size=14, color=GREEN, bold=True)
    text(s, "Nightline", Inches(0.9), Inches(2.75), Inches(11), Inches(1.1),
         size=60, color=FG, bold=True)
    text(s,
         "Street lights get repaired in the order they are reported.\n"
         "We repair them in the order that keeps people safe.",
         Inches(0.9), Inches(4.0), Inches(10), Inches(1.0), size=20, color=MUTED)
    text(s, f"Live model: {f['area']}  ·  {f['stats']['totalKm']} km of mapped street",
         Inches(0.9), Inches(6.4), Inches(11), Inches(0.3), size=12, color=MUTED)
    return s


def s_problem(prs, f):
    s = blank(prs)
    header(s, "THE PROBLEM", "A complaint queue is not a safety queue")
    text(s,
         "Repair queues run first-come, first-served. A broken light behind an empty block gets\n"
         "fixed before the footpath every hostel uses to reach the mess at midnight — because the\n"
         "empty one was reported first. Ask anyone who walks back from the library after 10pm.",
         Inches(0.8), Inches(2.05), Inches(11.7), Inches(1.2), size=17, color=MUTED)

    st = f["stats"]
    y = Inches(3.6)
    w = Inches(2.72)
    stat_card(s, Inches(0.8), y, w, f"{st['totalKm']} km", "of street mapped in our test area")
    stat_card(s, Inches(3.72), y, w, f"{st['darkKm']} km", "currently unlit", color=AMBER)
    stat_card(s, Inches(6.64), y, w, f"{st['highRiskSegments']}", "segments both BUSY and dark", color=RED)
    stat_card(s, Inches(9.56), y, w, f"{st['highRiskKm']} km", "— the part that actually matters", color=RED)

    text(s,
         "Everything is a priority, so nothing is. The missing input has never been light — it is who walks where.",
         Inches(0.8), Inches(5.6), Inches(11.7), Inches(0.5), size=16, color=FG, bold=True)
    return s


def s_finding(prs, f):
    s = blank(prs)
    header(s, "WHAT WE CHECKED FIRST", "The streetlight data does not exist. Anywhere.")
    text(s,
         "Before designing anything we queried OpenStreetMap for lighting data — here, then a second city:",
         Inches(0.8), Inches(2.0), Inches(11.7), Inches(0.4), size=16, color=MUTED)

    rows = [
        ("Streets mapped around MUJ / Dehmi Kalan", "284", FG),
        ("...of those, carrying any lighting tag", "9", AMBER),
        ("Streets in Chandigarh, a planned city", "29,136", FG),
        ("...of those, carrying any lighting tag", "178  (0.6%)", AMBER),
        ("Individual street lamps mapped, either city", "0", RED),
    ]
    y = Inches(2.55)
    for label, val, col in rows:
        card(s, Inches(0.8), y, Inches(11.7), Inches(0.62))
        text(s, label, Inches(1.1), y + Inches(0.16), Inches(8), Inches(0.4), size=15, color=FG)
        text(s, val, Inches(9.2), y + Inches(0.14), Inches(3), Inches(0.4),
             size=17, color=col, bold=True, align=PP_ALIGN.RIGHT)
        y += Inches(0.72)

    text(s,
         "That is not a gap in our plan — it is the problem itself.\n"
         "Nobody has this data, which is exactly why repair queues fall back to complaint order.",
         Inches(0.8), Inches(6.15), Inches(11.7), Inches(0.8), size=16, color=FG, bold=True)
    text(s,
         "So the product cannot look lighting up. It works out where lighting MATTERS, then collects only that.",
         Inches(0.8), Inches(6.95), Inches(11.7), Inches(0.35), size=13, color=GREEN)
    return s


def s_method(prs, f):
    s = blank(prs)
    header(s, "HOW IT WORKS", "Four steps. Only the third is unusual.")
    m = f["model"]
    steps = [
        ("1 · Take the street network",
         "Every road, footpath and campus lane from OpenStreetMap, as a graph with real distances."),
        ("2 · Find where students sleep, and where they go",
         f"{m['hostels']} hostel blocks and {m['destinations']} destinations — library, mess, food courts, academic\n"
         "blocks — all already named in OpenStreetMap by MUJ students themselves."),
        ("3 · Work out which paths people actually walk",
         f"Route every hostel to every destination and count segment usage: {m['modelledTrips']:,} modelled night\n"
         "trips. The shortcut to zanak scores high; the service lane behind admin scores zero."),
        ("4 · Multiply by darkness",
         "busy x dark = dangerous. That single ranking drives both the routing and the repair queue."),
    ]
    y = Inches(2.15)
    for i, (head, body) in enumerate(steps):
        card(s, Inches(0.8), y, Inches(11.7), Inches(1.0))
        text(s, head, Inches(1.1), y + Inches(0.14), Inches(11), Inches(0.35),
             size=17, color=GREEN if i == 2 else FG, bold=True)
        text(s, body, Inches(1.1), y + Inches(0.5), Inches(11), Inches(0.45), size=13, color=MUTED)
        y += Inches(1.16)

    text(s, "No machine learning. No training data. No API keys. Just graph theory over public map data.",
         Inches(0.8), Inches(6.85), Inches(11.7), Inches(0.4), size=14, color=MUTED)
    return s


def s_challenge(prs, f):
    s = blank(prs)
    header(s, "THE CHALLENGE QUESTION", '"How would you validate footfall where no official data exists?"')
    text(s, "We do not measure it. We derive it — and the derivation is checkable.",
         Inches(0.8), Inches(2.0), Inches(11.7), Inches(0.45), size=19, color=GREEN, bold=True)

    items = [
        ("The campus already encodes it",
         "Students walk from their block to the library, the mess, the food courts. Counting how often each\n"
         "path falls on those journeys is a structural estimate of foot traffic — no sensors, no surveys."),
        ("It is falsifiable on sight",
         "Anyone who studies here can check it in seconds: the B-block route to zanak ranks high, the service\n"
         "lane behind the water treatment plant ranks zero. A wrong answer would be obvious immediately."),
        ("It makes the survey tractable",
         f"{f['stats']['segments']:,} segments is impossible to survey by hand. The model says {f['stats']['highRiskSegments']} carry real night\n"
         "traffic — about {0} km. That is one evening of walking, and the app collects it.".format(f['stats']['highRiskKm'])),
    ]
    bullets(s, items, Inches(0.8), Inches(2.75), Inches(11.7), size=16, gap=0.78)
    return s


def s_routing(prs, f):
    s = blank(prs)
    header(s, "PROOF · ROUTING", "A safer walk usually costs almost nothing")
    h = f["headline"]
    r = f["routing"]

    y = Inches(2.0)
    w = Inches(3.72)
    stat_card(s, Inches(0.8), y, w, f"{h['cutPct']}%", "less time on unlit streets",
              color=GREEN, sub=f"{h['from']} to {h['to']}")
    stat_card(s, Inches(4.72), y, w, f"+{h['extraMeters']} m", f"extra walking ({h['extraPct']}%)",
              color=AMBER, sub="about 50 seconds")
    stat_card(s, Inches(8.64), y, w, f"{r['diverged']}/{r['total']}",
              "routes had a safer alternative", sub=f"median gain {r['medianCutPct']}% dark reduction")

    text(s, "Every landmark pair we tested", Inches(0.8), Inches(3.95), Inches(11.7), Inches(0.35),
         size=14, color=FG, bold=True)

    rows = f["bestValue"][:6]
    y = Inches(4.4)
    text(s, "ROUTE", Inches(0.9), y, Inches(5.6), Inches(0.3), size=10, color=MUTED, bold=True)
    text(s, "DARK BEFORE → AFTER", Inches(6.6), y, Inches(2.8), Inches(0.3), size=10, color=MUTED, bold=True)
    text(s, "DETOUR", Inches(9.6), y, Inches(1.3), Inches(0.3), size=10, color=MUTED, bold=True)
    text(s, "GAIN", Inches(11.2), y, Inches(1.3), Inches(0.3), size=10, color=MUTED, bold=True)
    y += Inches(0.32)
    for t in rows:
        nm = f"{t['from']} → {t['to']}"
        text(s, nm[:52], Inches(0.9), y, Inches(5.6), Inches(0.28), size=12, color=FG)
        text(s, f"{t['darkBefore']} m → {t['darkAfter']} m", Inches(6.6), y, Inches(2.8), Inches(0.28),
             size=12, color=MUTED)
        text(s, f"+{t['extraMeters']} m", Inches(9.6), y, Inches(1.3), Inches(0.28), size=12, color=AMBER)
        text(s, f"−{t['cutPct']}%", Inches(11.2), y, Inches(1.3), Inches(0.28), size=12, color=GREEN, bold=True)
        y += Inches(0.34)

    text(s, "We show both routes and the tradeoff. The walker chooses — the app does not quietly add a kilometre.",
         Inches(0.8), Inches(6.9), Inches(11.7), Inches(0.35), size=13, color=MUTED)
    return s


def s_queue(prs, f):
    s = blank(prs)
    header(s, "PROOF · REPAIR QUEUE", "Ranked by risk removed, not by who complained first")
    q = f["queue"][:6]

    text(s, f"Repairing five streets removes {f['queueTop5Pct']}% of all night pedestrian risk in the area.",
         Inches(0.8), Inches(1.95), Inches(11.7), Inches(0.45), size=19, color=GREEN, bold=True)

    y = Inches(2.65)
    text(s, "#", Inches(0.95), y, Inches(0.4), Inches(0.3), size=10, color=MUTED, bold=True)
    text(s, "STREET", Inches(1.5), y, Inches(6.2), Inches(0.3), size=10, color=MUTED, bold=True)
    text(s, "UNLIT", Inches(7.9), y, Inches(1.4), Inches(0.3), size=10, color=MUTED, bold=True)
    text(s, "FOOT TRAFFIC", Inches(9.3), y, Inches(1.8), Inches(0.3), size=10, color=MUTED, bold=True)
    text(s, "RISK REMOVED", Inches(11.0), y, Inches(1.5), Inches(0.3), size=10, color=MUTED, bold=True)
    y += Inches(0.38)

    for i, item in enumerate(q):
        card(s, Inches(0.8), y - Inches(0.08), Inches(11.7), Inches(0.52))
        text(s, str(i + 1), Inches(0.95), y, Inches(0.4), Inches(0.32), size=13, color=MUTED)
        text(s, item["label"][:56], Inches(1.5), y, Inches(6.2), Inches(0.32), size=13, color=FG)
        text(s, f"{item['meters']} m", Inches(7.9), y, Inches(1.4), Inches(0.32), size=13, color=MUTED)
        text(s, f"{item['avgExposure']:.3f}", Inches(9.3), y, Inches(1.8), Inches(0.32), size=13, color=MUTED)
        text(s, f"{item['benefitPct']}%", Inches(11.0), y, Inches(1.5), Inches(0.32),
             size=13, color=GREEN, bold=True)
        y += Inches(0.62)

    text(s,
         "Risk removed = modelled night foot traffic x unlit distance, as a share of the whole area.\n"
         "It turns \"fix the lights\" into a budget decision with a number attached.",
         Inches(0.8), Inches(6.55), Inches(11.7), Inches(0.7), size=13, color=MUTED)
    return s


def s_product(prs, f):
    s = blank(prs)
    header(s, "THE PRODUCT", "Three surfaces over one computation")
    maybe_image(s, "map", Inches(0.8), Inches(2.0), Inches(7.4))
    items = [
        ("Dark-zone map",
         "Red = busy and dark. Pick your block and destination, see both routes and the honest tradeoff."),
        ("Report a dark street",
         "Tap any path. It re-scores the map live and tells you where that street now sits in the queue."),
        ("Repair queue",
         "What the estates office should fix first, with the risk removed by each fix."),
        ("The agent",
         "Explains any ranking, drafts the complaint — you click Approve before it files."),
    ]
    bullets(s, items, Inches(8.6), Inches(2.1), Inches(3.9), size=13, gap=0.66)
    return s


def s_ai(prs, f):
    s = blank(prs)
    header(s, "WHERE THE AI SITS", "The computation is the product. The agent is the interface.")

    card(s, Inches(0.8), Inches(2.1), Inches(5.6), Inches(3.5))
    text(s, "The agent DOES", Inches(1.1), Inches(2.35), Inches(5), Inches(0.35),
         size=17, color=GREEN, bold=True)
    text(s,
         "· Turn \"walking home from the library at 11\"\n   into a route query\n\n"
         "· Explain why a street ranks where it does,\n   quoting the computed figures\n\n"
         "· Draft the municipal complaint\n\n"
         "· Wait for a human to approve before filing",
         Inches(1.1), Inches(2.85), Inches(5), Inches(2.6), size=13, color=MUTED)

    card(s, Inches(6.9), Inches(2.1), Inches(5.6), Inches(3.5))
    text(s, "The agent NEVER", Inches(7.2), Inches(2.35), Inches(5), Inches(0.35),
         size=17, color=RED, bold=True)
    text(s,
         "· Computes a route\n\n"
         "· Estimates foot traffic\n\n"
         "· Ranks a repair\n\n"
         "· States any number that did not come\n   back from a tool call",
         Inches(7.2), Inches(2.85), Inches(5), Inches(2.6), size=13, color=MUTED)

    text(s, "Turn the AI off and the map, the routing and the queue all still work. That is the test we designed to.",
         Inches(0.8), Inches(5.95), Inches(11.7), Inches(0.4), size=16, color=FG, bold=True)
    text(s, "It also means the demo cannot hallucinate a number a judge then checks.",
         Inches(0.8), Inches(6.45), Inches(11.7), Inches(0.4), size=13, color=MUTED)
    return s


def s_stack(prs, f):
    s = blank(prs)
    header(s, "BUILT WITH", "Free and open source, end to end")
    rows = [
        ("OpenStreetMap / Overpass API", "Street network, night destinations", "Free · no key"),
        ("NetworkX + custom Dijkstra", "Exposure model, dual-weight routing", "BSD"),
        ("Leaflet + CARTO tiles", "The map", "BSD · free tiles"),
        ("Next.js 16 + TypeScript", "App, APIs, computation layer", "MIT"),
        ("Gemini via AI SDK v7", "The agent layer only", "Free tier"),
    ]
    y = Inches(2.1)
    for a, b, c in rows:
        card(s, Inches(0.8), y, Inches(11.7), Inches(0.72))
        text(s, a, Inches(1.1), y + Inches(0.2), Inches(4.6), Inches(0.35), size=15, color=FG, bold=True)
        text(s, b, Inches(5.8), y + Inches(0.22), Inches(4.4), Inches(0.35), size=13, color=MUTED)
        text(s, c, Inches(10.3), y + Inches(0.22), Inches(2), Inches(0.35),
             size=12, color=GREEN, align=PP_ALIGN.RIGHT)
        y += Inches(0.86)

    text(s,
         "The graph is precomputed offline and shipped as a 182 KB file, so the live app needs no Python\n"
         "service and no paid infrastructure. Total running cost: zero.",
         Inches(0.8), Inches(6.5), Inches(11.7), Inches(0.7), size=13, color=MUTED)
    return s


def s_honest(prs, f):
    s = blank(prs)
    header(s, "WHAT IS REAL, WHAT IS NOT", "The part most decks leave out")

    card(s, Inches(0.8), Inches(2.1), Inches(5.6), Inches(3.3))
    text(s, "Real", Inches(1.1), Inches(2.35), Inches(5), Inches(0.35), size=17, color=GREEN, bold=True)
    text(s,
         f"· {f['stats']['totalKm']} km of real MUJ campus network\n\n"
         f"· {f['stats']['hostels']} hostel blocks and {f['stats']['destinations']} destinations, named in\n   OSM by MUJ students, not invented by us\n\n"
         f"· {f['stats']['litFromOsm']} segments with genuine OSM lighting tags\n\n"
         "· The model, routing and queue — all computed,\n   all reproducible, every figure in this deck\n   generated from the running code",
         Inches(1.1), Inches(2.85), Inches(5), Inches(2.4), size=13, color=MUTED)

    card(s, Inches(6.9), Inches(2.1), Inches(5.6), Inches(3.3))
    text(s, "Not yet real", Inches(7.2), Inches(2.35), Inches(5), Inches(0.35), size=17, color=AMBER, bold=True)
    text(s,
         f"· Lighting on the other {f['stats']['litSimulated']:,} segments is seeded\n   by road class — no lamp data exists anywhere\n\n"
         "· Foot traffic is modelled, never measured.\n   No ground truth exists to check it against\n\n"
         f"· Next step is the cheap one: one night of walking\n   to log the {f['stats']['highRiskSegments']} segments that actually matter —\n   which the app already collects, tap by tap",
         Inches(7.2), Inches(2.85), Inches(5), Inches(2.4), size=13, color=MUTED)

    text(s, "The engine is proven. The input is what a pilot supplies — and the model tells you exactly where to look.",
         Inches(0.8), Inches(5.75), Inches(11.7), Inches(0.4), size=15, color=FG, bold=True)
    return s


def s_close(prs, f):
    s = blank(prs)
    text(s, "Nightline", Inches(0.9), Inches(2.5), Inches(11), Inches(0.9), size=48, color=FG, bold=True)
    h = f["headline"]
    text(s,
         f"{f['queueTop5Pct']}% of night walking risk on this campus sits on five paths.\n"
         "Nobody knew which five, because nobody was counting who walks where.",
         Inches(0.9), Inches(3.6), Inches(11), Inches(1.2), size=21, color=MUTED)
    text(s,
         f"{h['from']} to {h['to']}: {h['cutPct']}% less time in the dark, for {h['extraMeters']} extra metre"
         f"{'s' if h['extraMeters'] != 1 else ''}.",
         Inches(0.9), Inches(5.0), Inches(11), Inches(0.5), size=21, color=GREEN, bold=True)
    return s


def main() -> None:
    f = load()
    prs = Presentation()
    prs.slide_width, prs.slide_height = W, H

    for fn in (
        s_title, s_problem, s_finding, s_method, s_challenge,
        s_routing, s_queue, s_product, s_ai, s_stack, s_honest, s_close,
    ):
        fn(prs, f)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    prs.save(OUT)
    kb = os.path.getsize(OUT) // 1024
    print(f"wrote {os.path.relpath(OUT)}  ({len(prs.slides.__iter__.__self__._sldIdLst)} slides, {kb} KB)")


if __name__ == "__main__":
    main()
